name: Damage Calculation Test
#name: ワークフローの名前
on:
#on: 必須動かす時のトリガーになるGitHubのイベント下の例だとpush。その他pullとか。
  push:
    branches:
      - master

jobs:
  build:
#このbuild:　はjobID文字列でつくる。英字または_で始める必要があり、英数字と-、_しか使用できない。
    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi! My name is
        FIRST_NAME: Monaco
        MIDDLE_NAME: The
        LAST_NAME: Rascasse
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    - uses: actions/checkout@v2
    - name: Use Node.js v10.14.2
      uses: actions/setup-node@v1
      with:
        node-version: '10.14.2'

    - run: yarn install
    - name: Install JUnit coverage reporter
      run: yarn add --dev jest-junit
    - name: Run tests with JUnit as reporter
      run: npx jest --ci --runInBand --reporters=default --reporters=jest-junit
      env:
        JEST_JUNIT_OUTPUT_DIR: "./junit/test-results.xml"
    - uses: actions/upload-artifact@v2
      with:
        path: ./junit/test-results.xml
      if: always()

